// <auto-generated />
using System;
using ECE.AA.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECE.AA.MyAirport.EF.Migrations
{
    [DbContext(typeof(AirportContext))]
    partial class AirportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECE.AA.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("ID_BAGAGE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CODE_IATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_CREATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESTINATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESCALE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_VOL")
                        .HasColumnType("int");

                    b.Property<byte>("PRIORITAIRE")
                        .HasColumnType("tinyint");

                    b.Property<string>("SSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STA")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID_BAGAGE");

                    b.HasIndex("ID_VOL");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("ECE.AA.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("ID_VOL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CIE")
                        .HasColumnType("int");

                    b.Property<string>("DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DHC")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JEX")
                        .HasColumnType("int");

                    b.Property<string>("LIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("PKG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_VOL");

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("ECE.AA.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("ECE.AA.MyAirport.EF.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("ID_VOL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
